-- Lenguaje DDL
-- ===============================

-- CREATE: Crear objetos
-- ALTER: Modificar objetos
-- DROP: Eliminar objetos

-- Crear una base de datos

CREATE DATABASE DEMO_DB;
GO

-- Crear una tabla

USE DEMO_DB;
GO

CREATE TABLE PRODUCTO(
	IDPROD INT NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO NUMERIC(12,2) NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY( IDPROD ),
	CONSTRAINT CK_PRODUCTO_PRECIO CHECK( PRECIO >= 0.0 )
);
GO

-- Agregar la columna STOCK

ALTER TABLE PRODUCTO
ADD STOCK INT NOT NULL DEFAULT 0;
GO

SP_HELP PRODUCTO
GO

-- Agregando un CHECK

ALTER TABLE PRODUCTO
ADD CONSTRAINT CK_Producto_Stock CHECK (STOCK >= 0);
GO

INSERT INTO PRODUCTO VALUES('PANTALON',120,50);
GO

INSERT INTO PRODUCTO VALUES('CAMISA',90,45);
GO

INSERT INTO PRODUCTO VALUES('ZAPATO',220,70);
GO


SELECT * FROM PRODUCTO;
GO

-- Eliminar la tabla

DROP TABLE PRODUCTO;
GO

-- Eliminar la base de datos

DROP DATABASE DEMO_DB;
GO


